### ISSUE TITLE
Cannot Find Amazon EC2 AMI

### ISSUE THREAD

**Issue by geordielad** [bibanul/tiger-geocoder#2]
Hello, There are great, and very detailed instructions, on setting up an EC2 instance using a pre built AMI. I cannot find the AMI on the Marketplace or Community AMIs.

![image](https://cloud.githubusercontent.com/assets/1714622/5240692/0f6d9d26-78d9-11e4-80d7-bf31a12b0216.png)

Thanks

**Comment by horizonchasers** [comment]
Do you have an update on when you expect the AMI to be released?  Is it possible to share the AMI directly with us before it is placed into the store?

**Comment by bibanul** [comment]
Amazon finished all the stuff and we got an email yesterday from them 
they are publishing it. It's imminent. I will post an update when it's 
done on their end.

**Comment by bibanul** [comment]
I have GREAT news. Amazon just published the AMI in the AWS Marketplace. They said it may take few hrs to fully replicate but it's officially available. Thanks for the patience. If you need help running it please shoot me a private message.

**Comment by horizonchasers** [comment]
That is GREAT news. Thanks for the update.

Chris
