### ISSUE TITLE
Database not starting

### ISSUE THREAD

**Issue by horizonchasers** [bibanul/tiger-geocoder#3]
We are not able to get the AMI to function properly following your directions. 

We have configured the PostgreSQL to use the custom directory "/mnt/postgres/data" as the data directory to which we have mounted the 120GB disk. While working on this case, we happen to end up in a bug with the OS configured in this AMI. For the sources list loaded for Ubuntu in the server, we are unable to update or upgrade the settings and also we are having difficulties with configuring the PostgreSQL to start its process. 

Upon our investigation, we find that the issue should be related to the bugs in the OS and hence the AMI. We have mounted the disks and have changed the configuration settings to use the custom data directory but then we are having issues with starting the service. 

Please refer to the error logs below:
==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--
root@tigergeo:~# apt-get update

Reading package lists... Error!
E: Could not open file /var/lib/dpkg/status - open (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.
------------------------
root@tigergeo:~# /etc/init.d/postgresql start

* Starting PostgreSQL 9.3 database server * Error: could not exec /usr/lib/postgresql/9.3/bin/pg_ctl /usr/lib/postgresql/9.3/bin/pg_ctl start -D /mnt/postgres/data -l /var/log/postgresql/postgresql-9.3-main.log -s -o -c config_file="/etc/postgresql/9.3/main/postgresql.conf" :
==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--

**Comment by bibanul** [comment]
Ok, few things to start off with. The AMI contains ALL ready to run software plus data. That means there is no need to reconfigure postgres or run apt-update or similar. When you fire up the AMI, it's ready and running as is. The only adjustments you need to make are the ones I mentioned regarding the memory tuning. The AMI comes configured with 4x30GB SSD for the TIGER data and it should be installed as such. There's a reason we want 4x SSDs to maximize the throughput. The actual SSD Monthly cost is insignificant to you. (few dollars).

If you step in the land of apt-update, you're on your own. We heavily tuned and compiled packages to make sure all runs "out of the box". some packages re not available in APT repos, we compiled them off sources. We're also updating the AMI periodically as new TIGER database comes out or if postgres needs patched. Once that happens it's very easy to either start a new AMI off the new image.

**Comment by bibanul** [comment]
send me a connect request on http://linkedin/in/bogdancirlig and we can chat to get you up and running on the AMI.
