### ISSUE TITLE
Can this code be adapted to run on a local server?

### ISSUE THREAD

**Issue by easherma** [bibanul/tiger-geocoder#8]
Hi there, 

Just curious if this project can be easily adapted to run on a local server, given the specs were met?

**Comment by bibanul** [comment]
initially we had it setup on local servers before we created AMIs for amazon. It's not a trivial job but you can install local. The part that's tricky is you will have to download and reinstall 100GB TIGER DB from us census. PM me if you're interested to go in that direction and we can consult for your project. I have it installed on a 120GB SSD and it's quite powerful on a similar 16GB machine thanks to the fast local SSD.
